### ISSUE TITLE
Texturas al revés

### ISSUE THREAD

**Issue by ailopez-o** [ailopez-o/42Barcelona-Cub3D#2]
La linea de la textura se carga al revés, lo de arriba abajo y viceversa.

![Screenshot 2023-04-29 at 20 53 10](https://user-images.githubusercontent.com/102803124/235319591-a5a546dc-29b0-4fcb-8085-6f10cb6bf0a6.png)
![Screenshot 2023-04-29 at 20 53 15](https://user-images.githubusercontent.com/102803124/235319599-37cfe015-3631-4741-bd77-0ac9faba81a6.png)

**Comment by ChewyToast** [comment]
Listo, textura invertida
