### ISSUE TITLE
Texturas y escala

### ISSUE THREAD

**Issue by ailopez-o** [ailopez-o/42Barcelona-Cub3D#3]
Cuando se usa una escala grande del mapa, en este caso 150 las texturas se "comprimen", de frente la textura debería verse como un cudrado. Supongo que será porque no estamos teniendo en cuenta la escala y cuanto mayor es el valor de la unidad de pared más se nota el efecto.
![Screenshot 2023-04-29 at 20 53 10](https://user-images.githubusercontent.com/102803124/235319638-ec1a9f5b-54e7-47a0-879c-7d013306e483.png)

**Comment by ChewyToast** [comment]
Ya esta, faltaba escalarlo
